### PR TITLE
Asciidoc version.

### PR DESCRIPTION
**Pull request by samwilson**

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Document that build script in your README please.  We may adopt that as a
standard.  Perhaps even make travis call ./build.sh.

I've been hesitant to add more than one file for builds (`travis.yml` up to
now, but not for any good reason.

**Comment by samwilson** [comment]
I started by having travis call build.sh, but then realised that I wanted them to be a bit different; of course it'd be better to pass a flag (e.g. --no-debug or something) that makes those changes (e.g. not calling lint) rather than repeating things.

I wondered about adding it as a makefile... but that's probably a bit of overkill. What do you think?

I'll edit the readme.

**Comment by sethwoodworth** [comment]
I am anti-makefiles.  I find the syntax is arcane, and I am a fan of [APL](https://en.wikipedia.org/wiki/APL_%28programming_language%29).  Bash is not
much better (or easier for new contributors) but at least doesn't require
xcode to be installed on OSX

**Comment by samwilson** [comment]
Yes, I think I agree re makefiles (and I'd not remembered that Macs don't come with make). I'll stick with bash. Now I'm just trying to get the deployment part working with Travis...

**Comment by sethwoodworth** [comment]
`travis setup releases` and then you have to add back `skip_cleanup: true`,
and possibly the branch configuration.

@rdhyee Fixed [this travis file](https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/compare/81f48b6d77e1bf7e11cd6f2006845bbd46659efa...master#diff-354f30a63fb0907d4ad57269548329e3R5)
earlier today.  In general the [current latest travis file](https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/fd80ff481f33d1acb757494e9e2ade481862ecec/.travis.yml)
in the Huck Finn repo is currently the best template.

**Comment by sethwoodworth** [comment]
This doesn't need to be able to build via travis to be merged.  Feel free to setup another PR with any additional changes you may have!

**Comment by samwilson** [comment]
Cool, thanks! :)

**Pull request merged**
